version: '3'

services:
    event_manager:
        container_name: event_manager
        hostname: event_manager
        build: 
            context: ./stacks
            dockerfile: Dockerfile
        restart: always
        environment:
            - WAIT_HOSTS_TIMEOUT=120
            - WAIT_HOSTS=event_db:3306
            - DATABASE_DRIVER=mysql
            - DATABASE_PORT=3306
            - DATABASE_HOST=event_db
            - DATABASE_NAME=events
            - DATABASE_USER=event_user
            - DATABASE_PASSWORD=event_user@123456
        depends_on: 
            - event_db
        volumes: 
            - ./:/var/www/html
            
            
    event_manager_nginx:
        container_name: event_manager_nginx
        hostname: event_manager_nginx
        build: 
            context: ./stacks
            dockerfile: Dockerfile_nginx
        environment:
            WAIT_HOSTS: event_manager:9000
        volumes:
            - ./:/var/www/html
        depends_on: 
            - event_manager
        ports:
            - "8003:80"

    event_db:
        image: mysql:5.7
        container_name: event_db
        hostname: event_db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=events
            - MYSQL_USER=event_user
            - MYSQL_PASSWORD=event_user@123456
        restart: unless-stopped
        volumes:
            - event_db_vol:/var/lib/mysql
        ports:
            - 33063:3306
            
volumes:
    event_db_vol:
        external: true

networks:
    default:
        external:
            name: event_manager.localhost
